[celostar-starrocks] Update other workflows to use runs-on runners (#1251)
Tests:
- [Run
Veracode](https://github.com/celonis/celostar-starrocks/actions/runs/10742748009)
(Please ignore the failure as that's not related to the build but from
veracode scan)
- [Build golden allin1
kw_others-dic](https://github.com/celonis/celostar-starrocks/actions/runs/10742478616)
- [Build dev env image
kw_others](https://github.com/celonis/celostar-starrocks/actions/runs/10742843634)
- [Celostar-Starrocks release:
kw_others-2](https://github.com/celonis/celostar-starrocks/actions/runs/10745172245)

diff --git a/.github/actions/build-allin1/action.yml b/.github/actions/build-allin1/action.yml
--- a/.github/actions/build-allin1/action.yml
+++ b/.github/actions/build-allin1/action.yml
@@ -70,19 +70,21 @@ runs:
         local_image: starrocks-allin1:${{inputs.image_tag}}
         remote_image: ghcr.io/celonis/celostar/starrocks-allin1:${{inputs.image_tag}}
 
-    - name: Clean up artifact image
-      if: ${{inputs.clean_up_artifact_image == 'true'}}
-      shell: bash
-      run: |
-        docker rmi -f $(docker images -q ${{inputs.artifact_image}})
-      continue-on-error: true
+# Skip this step as we are using runs-on runner which is ephemeral.
+#    - name: Clean up artifact image
+#      if: ${{inputs.clean_up_artifact_image == 'true'}}
+#      shell: bash
+#      run: |
+#        docker rmi -f $(docker images -q ${{inputs.artifact_image}})
+#      continue-on-error: true
 
-    - name: Clean up
-      if: ${{ always() }}
-      shell: bash
-      run: |
-        docker rmi -f $(docker images -q starrocks-allin1:${{inputs.image_tag}}) || true
-        docker system prune -f
-        docker volume prune -f
-        docker logout ghcr.io
-      continue-on-error: true
+# Skip this step as we are using runs-on runner which is ephemeral.
+#    - name: Clean up
+#      if: ${{ always() }}
+#      shell: bash
+#      run: |
+#        docker rmi -f $(docker images -q starrocks-allin1:${{inputs.image_tag}}) || true
+#        docker system prune -f
+#        docker volume prune -f
+#        docker logout ghcr.io
+#      continue-on-error: true
diff --git a/.github/actions/build-artifact/action.yml b/.github/actions/build-artifact/action.yml
--- a/.github/actions/build-artifact/action.yml
+++ b/.github/actions/build-artifact/action.yml
@@ -54,16 +54,17 @@ runs:
         local_image: starrocks-artifacts:${{inputs.image_tag}}
         remote_image: ghcr.io/celonis/celostar/starrocks-artifacts:${{inputs.image_tag}}
 
-    - name: Clean up
-      if: ${{ always() }}
-      shell: bash
-      run: |
-        # If the artifact image is not pushing to remote, we assume it will be used for later steps.
-        if [[ "${{inputs.to_push}}" == "true" ]]; then
-          echo "Cleaning up artifact image locally"
-          docker rmi -f $(docker images -q starrocks-artifacts:${{inputs.image_tag}}) || true
-        fi
-        docker system prune -f
-        docker volume prune -f
-        docker logout ghcr.io
-      continue-on-error: true
+# Skip this step as we are using runs-on runner which is ephemeral.
+#    - name: Clean up
+#      if: ${{ always() }}
+#      shell: bash
+#      run: |
+#        # If the artifact image is not pushing to remote, we assume it will be used for later steps.
+#        if [[ "${{inputs.to_push}}" == "true" ]]; then
+#          echo "Cleaning up artifact image locally"
+#          docker rmi -f $(docker images -q starrocks-artifacts:${{inputs.image_tag}}) || true
+#        fi
+#        docker system prune -f
+#        docker volume prune -f
+#        docker logout ghcr.io
+#      continue-on-error: true
diff --git a/.github/actions/presubmit-test/action.yml b/.github/actions/presubmit-test/action.yml
--- a/.github/actions/presubmit-test/action.yml
+++ b/.github/actions/presubmit-test/action.yml
@@ -34,12 +34,13 @@ runs:
       run: |
           echo "The test branch is ${{inputs.branch}}" >> $GITHUB_STEP_SUMMARY
 
-    - name: clean up
-      if: ${{ always() }}
-      shell: bash
-      run: |
-        docker kill ${{ env.container_id }} || true
-        docker system prune -f
-        docker volume prune -f
-        docker logout ghcr.io
-      continue-on-error: true
+# Skip this step as we are using runs-on runner which is ephemeral.
+#    - name: clean up
+#      if: ${{ always() }}
+#      shell: bash
+#      run: |
+#        docker kill ${{ env.container_id }} || true
+#        docker system prune -f
+#        docker volume prune -f
+#        docker logout ghcr.io
+#      continue-on-error: true
