Move first-commit check to presubmit test (#1372)
## Why I'm doing:
Move the check to `presubmit test` so that we can run it in every PR.

## What I'm doing:
move the check from `integration test` to `presubmit test`

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression
evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with
different default values
- [ ] Policy changes: use new policy to replace old one, functionality
automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or
behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be
auto-backported to the target branch
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

diff --git a/.github/workflows/celonis_presubmit_test.yml b/.github/workflows/celonis_presubmit_test.yml
--- a/.github/workflows/celonis_presubmit_test.yml
+++ b/.github/workflows/celonis_presubmit_test.yml
@@ -34,6 +34,31 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: check Celonis's first commit
+        shell: bash
+        run: |
+          first_commit=$(git log --grep="\[Refactor\] Transplant Celonis commits from branch-2.4-ubuntu to" --format="%H")
+          
+          if [ -z $first_commit ]; then
+          echo "First commit Not found, existing..."
+          exit 1
+          else
+          echo "First commit found - $first_commit"
+          fi
+          
+          celonis_first_commit_date=$(git log $first_commit --format="%at" -n 1)
+          starrocks_latest_commit_date=$(git log $first_commit^ --format="%at" -n 1)
+          
+          # check time
+          if [ "$celonis_first_commit_date" -gt "$starrocks_latest_commit_date" ]; then
+          echo "Celonis's first commit should be on the top of the latest Starrocks' commit"
+          exit 1
+          fi
+          
+          echo "Time check passed" 
 
       - name: Pull dev env image
         run: |
